// This file is generated by VectorSigma v1.2.0-7-g64664f8 (commit: 64664f8, built at: 2026-04-28T16:36:49Z.1.0). DO NOT EDIT.
package orchestrator_test

import (
	"testing"

	"github.com/mhersson/contextmatrix-runner/internal/orchestrator"
)

func TestContextMatrixOrchestrator_Run(t *testing.T) {
	type fields struct {
		Context       *orchestrator.Context
		CurrentState  orchestrator.StateName
		ExtendedState *orchestrator.ExtendedState
		StateConfigs  map[orchestrator.StateName]orchestrator.StateConfig
	}
	tests := []struct {
		name   string
		fields fields
	}{
		{name: "Run the machine"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fsm := orchestrator.New()
			fsm.Run()
		})
	}
}
