// This file is generated by VectorSigma v1.2.0-7-g64664f8 (commit: 64664f8, built at: 2026-04-28T16:36:49Z.1.0). DO NOT EDIT.
package orchestrator

import (
	"fmt"
	"log/slog"
	"os"
)

type (
	StateName  string
	ActionName string
	GuardName  string
)

const (
	Brainstorming          StateName = "Brainstorming"
	CheckingRevisionBudget StateName = "CheckingRevisionBudget"
	ClaimingCard           StateName = "ClaimingCard"
	Completing             StateName = "Completing"
	CreatingSubtasks       StateName = "CreatingSubtasks"
	Diagnosing             StateName = "Diagnosing"
	Documenting            StateName = "Documenting"
	Executing              StateName = "Executing"
	FinalState             StateName = "FinalState"
	Finalizing             StateName = "Finalizing"
	Halting                StateName = "Halting"
	HandlingError          StateName = "HandlingError"
	InitialState           StateName = "InitialState"
	Initializing           StateName = "Initializing"
	Planning               StateName = "Planning"
	Replanning             StateName = "Replanning"
	Reviewing              StateName = "Reviewing"
	Routing                StateName = "Routing"
)

const (
	ClaimCard                 ActionName = "ClaimCard"
	CreateSubtaskCards        ActionName = "CreateSubtaskCards"
	DecideStartingPhase       ActionName = "DecideStartingPhase"
	EmitAutonomousHalted      ActionName = "EmitAutonomousHalted"
	HandleError               ActionName = "HandleError"
	IncrementRevisionAttempts ActionName = "IncrementRevisionAttempts"
	Initialize                ActionName = "Initialize"
	PushBranchesAndOpenPRs    ActionName = "PushBranchesAndOpenPRs"
	RunBrainstormingDialogue  ActionName = "RunBrainstormingDialogue"
	RunDiagnosisPhase         ActionName = "RunDiagnosisPhase"
	RunDocumentPhase          ActionName = "RunDocumentPhase"
	RunExecutePhaseParallel   ActionName = "RunExecutePhaseParallel"
	RunPlanPhase              ActionName = "RunPlanPhase"
	RunReplanPhase            ActionName = "RunReplanPhase"
	RunReviewPhase            ActionName = "RunReviewPhase"
	TransitionCardToDone      ActionName = "TransitionCardToDone"
)

const (
	AllRemainingBlocked                GuardName = "AllRemainingBlocked"
	HasNewSubtasksFromDecomposition    GuardName = "HasNewSubtasksFromDecomposition"
	HasUnfinishedSubtasks              GuardName = "HasUnfinishedSubtasks"
	IsAutonomousAndMaxAttemptsExceeded GuardName = "IsAutonomousAndMaxAttemptsExceeded"
	IsError                            GuardName = "IsError"
	IsRevise                           GuardName = "IsRevise"
	NeedsBrainstorm                    GuardName = "NeedsBrainstorm"
	NeedsDiagnosis                     GuardName = "NeedsDiagnosis"
	NeedsReview                        GuardName = "NeedsReview"
	SubtasksDoneNoDocs                 GuardName = "SubtasksDoneNoDocs"
)

const maxStateDepth = 5

// Action represents a function that can be executed in a state and may return an error.
type Action struct {
	Name    ActionName
	Params  []string
	Execute func(...string) error
}

// Guard represents a function that returns a boolean indicating if a transition should occur.
type Guard struct {
	Name   GuardName
	Params []string
	Check  func(...string) bool
	Action *Action
}

// StateConfig holds the actions and guards for a state.
type StateConfig struct {
	Actions     []Action
	Guards      []Guard
	Transitions map[int]StateName // Maps guard index to the next state
	Composite   CompositeState
}

type CompositeState struct {
	InitialState StateName
	StateConfigs map[StateName]StateConfig
}

// VectorSigma represents the Finite State Machine (fsm) for VectorSigma.
type ContextMatrixOrchestrator struct {
	Context       *Context
	CurrentState  StateName
	ExtendedState *ExtendedState
	StateConfigs  map[StateName]StateConfig
}

// New initializes a new FSM.
func New() *ContextMatrixOrchestrator {
	logLevel := new(slog.LevelVar)
	logLevel.Set(slog.LevelInfo)

	if os.Getenv("CONTEXTMATRIXORCHESTRATOR_DEBUG") != "" {
		logLevel.Set(slog.LevelDebug)
	}

	fsm := &ContextMatrixOrchestrator{
		Context:       &Context{Logger: slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: logLevel}))},
		CurrentState:  InitialState,
		ExtendedState: &ExtendedState{},
		StateConfigs:  make(map[StateName]StateConfig),
	}
	fsm.StateConfigs[Brainstorming] = StateConfig{
		Actions: []Action{
			{Name: RunBrainstormingDialogue, Execute: fsm.RunBrainstormingDialogueAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: Planning,
		},
	}
	fsm.StateConfigs[CheckingRevisionBudget] = StateConfig{
		Actions: []Action{
			{Name: IncrementRevisionAttempts, Execute: fsm.IncrementRevisionAttemptsAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsAutonomousAndMaxAttemptsExceeded, Params: []string{}, Check: fsm.IsAutonomousAndMaxAttemptsExceededGuard},
		},
		Transitions: map[int]StateName{
			0: Halting,
			1: Replanning,
		},
	}
	fsm.StateConfigs[ClaimingCard] = StateConfig{
		Actions: []Action{
			{Name: ClaimCard, Execute: fsm.ClaimCardAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: Routing,
		},
	}
	fsm.StateConfigs[Completing] = StateConfig{
		Actions: []Action{
			{Name: TransitionCardToDone, Execute: fsm.TransitionCardToDoneAction, Params: []string{}},
		},
		Guards: []Guard{},
		Transitions: map[int]StateName{
			0: FinalState,
		},
	}
	fsm.StateConfigs[CreatingSubtasks] = StateConfig{
		Actions: []Action{
			{Name: CreateSubtaskCards, Execute: fsm.CreateSubtaskCardsAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: Executing,
		},
	}
	fsm.StateConfigs[Diagnosing] = StateConfig{
		Actions: []Action{
			{Name: RunDiagnosisPhase, Execute: fsm.RunDiagnosisPhaseAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: Planning,
		},
	}
	fsm.StateConfigs[Documenting] = StateConfig{
		Actions: []Action{
			{Name: RunDocumentPhase, Execute: fsm.RunDocumentPhaseAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: Reviewing,
		},
	}
	fsm.StateConfigs[Executing] = StateConfig{
		Actions: []Action{
			{Name: RunExecutePhaseParallel, Execute: fsm.RunExecutePhaseParallelAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
			{Name: AllRemainingBlocked, Params: []string{}, Check: fsm.AllRemainingBlockedGuard},
			{Name: HasNewSubtasksFromDecomposition, Params: []string{}, Check: fsm.HasNewSubtasksFromDecompositionGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: HandlingError,
			2: CreatingSubtasks,
			3: Documenting,
		},
	}

	fsm.StateConfigs[Finalizing] = StateConfig{
		Actions: []Action{
			{Name: PushBranchesAndOpenPRs, Execute: fsm.PushBranchesAndOpenPRsAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: Completing,
		},
	}
	fsm.StateConfigs[Halting] = StateConfig{
		Actions: []Action{
			{Name: EmitAutonomousHalted, Execute: fsm.EmitAutonomousHaltedAction, Params: []string{}},
		},
		Guards: []Guard{},
		Transitions: map[int]StateName{
			0: FinalState,
		},
	}
	fsm.StateConfigs[HandlingError] = StateConfig{
		Actions: []Action{
			{Name: HandleError, Execute: fsm.HandleErrorAction, Params: []string{}},
		},
		Guards: []Guard{},
		Transitions: map[int]StateName{
			0: FinalState,
		},
	}
	fsm.StateConfigs[InitialState] = StateConfig{
		Actions: []Action{},
		Guards:  []Guard{},
		Transitions: map[int]StateName{
			0: Initializing,
		},
	}
	fsm.StateConfigs[Initializing] = StateConfig{
		Actions: []Action{
			{Name: Initialize, Execute: fsm.InitializeAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: ClaimingCard,
		},
	}
	fsm.StateConfigs[Planning] = StateConfig{
		Actions: []Action{
			{Name: RunPlanPhase, Execute: fsm.RunPlanPhaseAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: CreatingSubtasks,
		},
	}
	fsm.StateConfigs[Replanning] = StateConfig{
		Actions: []Action{
			{Name: RunReplanPhase, Execute: fsm.RunReplanPhaseAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: CreatingSubtasks,
		},
	}
	fsm.StateConfigs[Reviewing] = StateConfig{
		Actions: []Action{
			{Name: RunReviewPhase, Execute: fsm.RunReviewPhaseAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
			{Name: IsRevise, Params: []string{}, Check: fsm.IsReviseGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: CheckingRevisionBudget,
			2: Finalizing,
		},
	}
	fsm.StateConfigs[Routing] = StateConfig{
		Actions: []Action{
			{Name: DecideStartingPhase, Execute: fsm.DecideStartingPhaseAction, Params: []string{}},
		},
		Guards: []Guard{
			{Name: IsError, Params: []string{}, Check: fsm.IsErrorGuard},
			{Name: NeedsBrainstorm, Params: []string{}, Check: fsm.NeedsBrainstormGuard},
			{Name: NeedsDiagnosis, Params: []string{}, Check: fsm.NeedsDiagnosisGuard},
			{Name: HasUnfinishedSubtasks, Params: []string{}, Check: fsm.HasUnfinishedSubtasksGuard},
			{Name: SubtasksDoneNoDocs, Params: []string{}, Check: fsm.SubtasksDoneNoDocsGuard},
			{Name: NeedsReview, Params: []string{}, Check: fsm.NeedsReviewGuard},
		},
		Transitions: map[int]StateName{
			0: HandlingError,
			1: Brainstorming,
			2: Diagnosing,
			3: Executing,
			4: Documenting,
			5: Reviewing,
			6: Planning,
		},
	}

	return fsm
}

// Run handles the state transitions based on the current state.
func (fsm *ContextMatrixOrchestrator) Run() error {
	return run(fsm, fsm.StateConfigs, 0)
}

func run(fsm *ContextMatrixOrchestrator, stateConfigs map[StateName]StateConfig, depth int) error {
	if depth > maxStateDepth {
		return fmt.Errorf("max state depth exceeded")
	}

	for {
		// If we are in the FinalState, exit the FSM
		if fsm.CurrentState == FinalState {
			// Reset to the Initial State in case the FSM is run in a loop
			fsm.CurrentState = InitialState

			return fsm.ExtendedState.Error
		}

		config, exists := stateConfigs[fsm.CurrentState]

		if !exists {
			fsm.Context.Logger.Error("missing config", "state", fsm.CurrentState)

			return fmt.Errorf("missing config for state: %s", fsm.CurrentState)
		}

		if config.Composite.StateConfigs != nil {
			parentState := fsm.CurrentState
			// Recursively run the composite state machine
			fsm.CurrentState = config.Composite.InitialState
			fsm.Context.Logger.Debug("entering composite state", "state", parentState, "initial", fsm.CurrentState)
			err := run(fsm, config.Composite.StateConfigs, depth+1)
			if err != nil {
				fsm.Context.Logger.Error("composite state machine failed", "state", fsm.CurrentState, "error", err)
				fsm.ExtendedState.Error = err
			}

			fsm.Context.Logger.Debug("exiting composite state", "state", parentState)
			fsm.CurrentState = parentState
		} else {
			// Execute all actions for the current state
			err := runAllActions(fsm.Context, fsm.CurrentState, config.Actions)
			if err != nil {
				fsm.Context.Logger.Error("action failed", "state", fsm.CurrentState, "error", err)
				fsm.ExtendedState.Error = err
			}
		}

		// Check guards and determine the next state
		nextState, err := runAllGuards(fsm.Context, fsm.CurrentState, config)
		if err != nil {
			// Guarded actions will always transition to the FinalState
			fsm.ExtendedState.Error = err
			fsm.CurrentState = FinalState
		}
		if nextState != "" {
			fsm.CurrentState = nextState

			continue
		}

		// Check for unguarded transition
		if nextState, exists := config.Transitions[len(config.Guards)]; exists {
			fsm.Context.Logger.Debug("unguarded transition", "current", fsm.CurrentState, "next", nextState)
			fsm.CurrentState = nextState
		}
	}

}

func runAllActions(context *Context, currentState StateName, actions []Action) error {
	for _, action := range actions {
		context.Logger.Debug("executing", "action", action.Name, "state", currentState)

		if err := action.Execute(action.Params...); err != nil {
			return err
		}
	}

	return nil
}

func runAllGuards(context *Context, currentState StateName, config StateConfig) (StateName, error) {
	for guardIndex, guard := range config.Guards {
		if guard.Check(guard.Params...) {
			if guard.Action != nil {
				action := guard.Action
				if err := action.Execute(action.Params...); err != nil {
					context.Logger.Debug("guarded action failed", "state", currentState,
						"guard", guard.Name, "action", action.Name, "error", err)

					return "", err
				}
			}

			// Transition to the state mapped to this guard index
			if nextState, exists := config.Transitions[guardIndex]; exists {
				context.Logger.Debug("guarded transition", "guard", guard.Name, "current", currentState, "next", nextState)

				return nextState, nil
			}
		}
	}

	return "", nil
}
