#!/bin/sh
# Worker entrypoint for the cc-orchestrated runner path.
#
# Bootstraps:
#   - /workspace (created empty; the runner-driven plan/execute phases
#     populate it via git clone / git worktree)
#   - $HOME/.claude.json (MCP server config) from MCP_URL + MCP_API_KEY env
#   - A git credential helper that reads CM_GIT_TOKEN from the per-exec
#     env at git-call time (the runner injects a freshly-minted token on
#     every docker exec, so long-running cards stay authenticated past
#     the App installation token's 1-hour TTL)
#   - $HOME/.claude/skills (best-effort; may be populated by a sidecar)
#   - Identifies as runner@contextmatrix.local for any commits the agents
#     produce
#
# Then sleeps forever. The runner uses Docker SDK ContainerExecCreate
# to spawn each Claude subprocess on demand.
#
# IMPORTANT: the worker container runs as a non-root user (USER user in
# Dockerfile.orchestrated). Use $HOME, not /root, for any user-owned
# config; otherwise mkdir/write fails and `set -eu` exits the entrypoint
# before `sleep infinity`, causing the container to die immediately.
set -eu

# Source secrets file if present (same pattern as the cc-legacy entrypoint).
if [ -f /run/cm-secrets/env ]; then
    set -a
    # shellcheck disable=SC1091
    . /run/cm-secrets/env
    set +a
    rm -f /run/cm-secrets/env 2>/dev/null || true
fi

# Workspace dirs (writable by the running user).
mkdir -p /workspace 2>/dev/null || true
mkdir -p "$HOME/.claude/skills"

# ----- Task skills (start) -----
# Filesystem-mounted Claude Code skills.
HOST_SKILLS_DIR="${CM_HOST_SKILLS_DIR:-/host-skills}"
if [ -d "$HOST_SKILLS_DIR" ]; then
    if [ -n "${CM_TASK_SKILLS_SET:-}" ]; then
        # Explicit selection (CSV; may be empty after splitting).
        OLDIFS="$IFS"
        IFS=','
        # shellcheck disable=SC2086
        set -- ${CM_TASK_SKILLS:-}
        IFS="$OLDIFS"
        for s in "$@"; do
            case "$s" in
                ""|*[!A-Za-z0-9._-]*|.*|-*) continue ;;
            esac
            if [ -d "$HOST_SKILLS_DIR/$s" ]; then
                cp -r "$HOST_SKILLS_DIR/$s" "$HOME/.claude/skills/"
            else
                echo "WARN: requested task skill '$s' not found in $HOST_SKILLS_DIR" >&2
            fi
        done
    else
        # No constraint — mount the full set.
        for d in "$HOST_SKILLS_DIR"/*/; do
            [ -d "$d" ] || continue
            cp -r "$d" "$HOME/.claude/skills/"
        done
    fi
fi
# ----- Task skills (end) -----

# Identity for any commits agents land in worktrees inside this container.
git config --global user.name "ContextMatrix Runner"
git config --global user.email "runner@contextmatrix.local"

# ----- Git credential helper (start) -----
# The helper script reads CM_GIT_TOKEN from its own process env at
# git-call time — NOT from a file on disk and NOT from this entrypoint
# shell's env. The runner sets CM_GIT_TOKEN per `docker exec`, so every
# git subprocess sees a freshly-minted, non-expired token. No token
# ever lands on disk inside the worker.
#
# gh CLI honours GH_TOKEN directly from the same per-exec env, so it
# needs no extra wiring here.
#
# Unlike the legacy single-repo entrypoint, the orchestrated path may
# touch multiple GitHub hosts/repos within one card, so we register the
# helper as the global credential.helper rather than per-host.
_cred_helper="$HOME/.cm-git-cred-helper.sh"
cat > "$_cred_helper" <<'HELPER_EOF'
#!/bin/sh
# Generated by contextmatrix-runner orchestrated entrypoint. Do not edit.
# Reads the token from env at the moment git asks for credentials; the
# runner injects CM_GIT_TOKEN on every docker exec.
if [ "${1:-}" = "get" ]; then
    printf 'username=x-access-token\n'
    printf 'password=%s\n' "${CM_GIT_TOKEN:-}"
fi
HELPER_EOF
chmod 700 "$_cred_helper"
git config --global --replace-all credential.helper "!${_cred_helper}"
unset _cred_helper
# ----- Git credential helper (end) -----

# MCP config (Claude Code reads $HOME/.claude.json on startup).
if [ -n "${MCP_URL:-}" ] && [ -n "${MCP_API_KEY:-}" ]; then
    cat > "$HOME/.claude.json" <<EOF
{
  "mcpServers": {
    "contextmatrix": {
      "type": "http",
      "url": "${MCP_URL}",
      "headers": {"Authorization": "Bearer ${MCP_API_KEY}"}
    }
  }
}
EOF
fi

# Scrub MCP credentials from the env so spawned processes (every claude
# exec, every Bash tool) cannot read them directly. Claude Code reads
# the bearer from $HOME/.claude.json — the env vars are only needed at
# bootstrap. (CM_GIT_TOKEN / GH_TOKEN are not in this shell at all —
# they arrive only as per-exec env from the runner.)
unset MCP_API_KEY MCP_URL

# Sleep forever; the runner drives all CC invocations via docker exec.
exec sleep infinity
